# Generated by Django 5.1.7 on 2025-06-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0004_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clases/'),
        ),
    ]
