# Generated by Django 5.1.7 on 2025-06-04 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0005_clase_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clase',
            name='tipo',
        ),
        migrations.AddField(
            model_name='clase',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='gimnasio.categoriaclase'),
        ),
    ]
