# Generated by Django 5.1.7 on 2025-06-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0006_categoriaclase_remove_clase_tipo_clase_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaclase',
            name='slug',
            field=models.SlugField(blank=True, max_length=60),
        ),
    ]
