# Generated by Django 5.1.7 on 2025-06-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0007_categoriaclase_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaclase',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
