# Generated by Django 5.1.7 on 2025-06-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0009_reservahorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaclase',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
